package leetcode.Heap;

public class UglyNumberII_264 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

	public int nthUglyNumber(int n) {
        int [] primes = new int [] {2,3,5};
		int [] idx = new int [3];
		int [] ugly = new int [n];
		
		ugly[0] = 1;
		//new ugly number is generated by multiplying a prime with previous generated ugly number
		for(int i=1;i<n;i++){
			//initial ugly i with max integer
			ugly[i] = Integer.MAX_VALUE;
			//get next ugly number
			for(int j=0;j<primes.length;j++){
				ugly[i] = Math.min(ugly[i],primes[j]*ugly[idx[j]]);
			}
			//make index++;,remove dulplicate
			for(int j=0;j<primes.length;j++){
				while(ugly[i]>=primes[j]*ugly[idx[j]]) idx[j]++;
			}
		}
		
		return ugly[n-1];
    }
}
